### ISSUE TITLE
Link Issue

### ISSUE THREAD

**Issue by Miah747** [bhogancvtc/website#3]
``` css
body#lchase1 a:link, a:active, a:visited, a:hover, a:focus {
  color: #ff0;
  text-decoration: none;
}
```

The main a link is fine, but everything after is applying to all a tags on the page.
